# This is a basic workflow to help you get started with Actions

name: Javadocs

on:
  push:
    branches:
      - master
      - development
  workflow_dispatch:

jobs:
  deploy_release_docs:
    runs-on: ubuntu-latest
    #if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 16

      - name: Fetch project version # Fetch current project version
        shell: bash
        run: echo "::set-output name=PROJECT_VERSION::$(./gradlew printVersion | head -n 1)"
        id: version

      - name: Build Javadocs
        run: |
          echo "Building javadocs with gradle"
          ./gradlew javadoc
          echo "Moving to javadocs directory:"
          cd build/docs/javadoc
          echo "Creating .nojekyll to have Github pages deploy html as is:"
          touch .nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: docs # The branch the action should deploy to.
          target-folder: ${{ steps.version.PROJECT_VERSION }}
          folder: build/docs/javadoc # The folder the action should deploy.
